apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n76hk3mwn-python
  janus-idp.io/tekton: n76hk3mwn-python
  backstage.io/kubernetes-id: n76hk3mwn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n76hk3mwn-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
