apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n76hk3mwn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n76hk3mwn-python 
  name: n76hk3mwn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: n76hk3mwn-python 
